app:
  apiurl: https://api.upcitemdb.com/prod/trial/lookup?upc=
  campus: Stanton
  darkthemes: ElegantDark,AMOLED
  icon: ./img/favicon.ico
  lightthemes: Aqua,DTCC
  name: Printer Inventory
  searchmode: models
  theme: ElegantDark
  version: 1.0.1
database:
  host: localhost
  name: printers_db
  password: slurmsmackenzie
  port: 3306
  tablename: inventory
  username: ralphmacchio
directories:
  json: ./json
docs:
  guide: ./docs/guide.html
  pdoc: ./docs/apidocs/index.html
logs:
  main: ./logs/prt-inventory.log
preferences:
  mute: 1
  safetynet: 0
  selectedcolumns: description,printers,code,upc,stock,part_num,color,type,comments,linked_codes
  selectedindices: 1,2,3,4,5,6,7,9,10,11
  unusedcolumns: brand,yield,needed
  unusedindices: 0,8,12
sounds:
  fail: ./wav/fail.wav
  success: ./wav/success.wav
